### PR TITLE
use route also for update-api call

### PR DESCRIPTION
**Pull request by tk-s**

### CODE REVIEW

**Comment by nWidart** [comment]
Thank you for the contribution. Could you please squash those 2 commits together ?

**Comment by nWidart** [comment]
Awesome! :+1:

**Comment by nWidart** [comment]
I saw, too late, that this PR was sent to `master` branch, please in the future send PR to the `develop` branches, thanks.

**Comment by tk-s** [comment]
Oh, sorry! i’ll do!

Am 08.09.2015 um 08:47 schrieb Nicolas Widart <notifications@github.com<mailto:notifications@github.com>>:


I saw, too late, that this PR was sent to master branch, please in the future send PR to the develop branches, thanks.

**Pull request merged**
